### PR TITLE
Fix activation of MSS with no stream descriptors

### PR DESCRIPTION
**Pull request by brbeec**
The platform's IMediaStreamSourceFactory implementation will throw an error in its factory methods if a valid IMediaStreamDescriptor is not provided.

This change works around this issue by using IActivationFactory::ActivateInstance() to activate an MSS without a valid IMediaStreamDescriptor.

### CODE REVIEW

File: FFmpegInterop/FFmpegInteropMSS.h [hunk 1]
```diff
@@ -24,7 +24,6 @@
 #include "MediaThumbnailData.h"
 
 using namespace Platform;
-using namespace Windows::Foundation;
```
Comment (dcarpente) [inline FFmpegInterop/FFmpegInteropMSS.h:27]: Why are we removing this, was there some naming collision?

Comment (dcarpente) [reply FFmpegInterop/FFmpegInteropMSS.h:27]: If it's just a stylistic change, I don't mind, I'm approving anyway

**Review by dcarpente — APPROVED** [review]

File: FFmpegInterop/FFmpegInteropMSS.h (hunk 1 above)
Comment (brbeec) [reply FFmpegInterop/FFmpegInteropMSS.h:27]: There were compilation errors from ambiguous symbols after I included wrl.h. In general it's bad practice to write "using namespace" like this in header files. [C++ Core Guidelines SF.7: Don’t write using namespace at global scope in a header file](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file)
